"""record what actually ran: code, stdout, error on experiments

Revision ID: 426c7271fd50
Revises: 852b0aab5777
Create Date: 2026-09-03 08:42:11.092574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426c7271fd50'
down_revision: Union[str, Sequence[str], None] = '852b0aab5777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('stdout', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('stdout')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
